/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/reading/[poem_id]`; params?: Router.UnknownInputParams; } | { pathname: `/../services/dataService`; params?: Router.UnknownInputParams; } | { pathname: `/../types/shahname`; params?: Router.UnknownInputParams; } | { pathname: `/../services/poemLoader`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/reading/[poem_id]`, params: Router.UnknownInputParams & { poem_id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/reading/[poem_id]`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/dataService`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/shahname`; params?: Router.UnknownOutputParams; } | { pathname: `/../services/poemLoader`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/reading/[poem_id]`, params: Router.UnknownOutputParams & { poem_id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/reading/[poem_id]${`?${string}` | `#${string}` | ''}` | `/../services/dataService${`?${string}` | `#${string}` | ''}` | `/../types/shahname${`?${string}` | `#${string}` | ''}` | `/../services/poemLoader${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/reading/[poem_id]`; params?: Router.UnknownInputParams; } | { pathname: `/../services/dataService`; params?: Router.UnknownInputParams; } | { pathname: `/../types/shahname`; params?: Router.UnknownInputParams; } | { pathname: `/../services/poemLoader`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/reading/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/reading/[poem_id]`, params: Router.UnknownInputParams & { poem_id: string | number; } };
    }
  }
}
